### ISSUE TITLE
금요귀가 신청은 화요일까지 아닌가요?

### ISSUE THREAD

**Issue by ldhdev916** [jeamxn/dipull#358]
https://github.com/jeamxn/dipull/blob/d0952688847b0259b4e69741f53066ddd6a1a6e1/src/app/stay/homecoming/grant/%5Bid%5D/put.ts#L44
https://github.com/jeamxn/dipull/blob/d0952688847b0259b4e69741f53066ddd6a1a6e1/src/utils/date.ts#L37-L50
https://github.com/jeamxn/dipull/blob/d0952688847b0259b4e69741f53066ddd6a1a6e1/src/utils/date.ts#L15-L25

**Comment by jeamxn** [comment]
아 이런

**Comment by jeamxn** [comment]
감사합니다

**Comment by jeamxn** [comment]
ㅠㅜㅠ
